spring:
  application:
    name: OTPAuth
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: your_smtp_host
    port: your_smtp_port
    username: your_username
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
config:
  jwt:
    iss: your_iss
    expiration:
      access_token: 5
      refresh_token: 15
  verification:
    code:
      length: 6
      expiration: 5
      resend_threshold: 60
  email:
    from: your_email_address